<a href="https://colab.research.google.com/github/flash1zx/Machine-learningE/blob/main/Hello.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/Customers.csv')

In [ ]:
print(data)

In [ ]:
print(type(data))

In [ ]:
data.head(10)

In [ ]:
data.tail(7)

In [ ]:
data.info()

In [ ]:
data.describe()

In [ ]:
data.columns

In [ ]:
data.dtypes

In [ ]:
data.shape

In [ ]:
data.index

In [ ]:
print(type(data.Profession))

In [ ]:
data['Gender'].unique()

In [ ]:
data['Gender'].value_counts()

In [ ]:
data['Age'].mean()

In [ ]:
data.loc[1000]

In [ ]:
data.iloc[1000]

In [ ]:
data.isnull().sum()

In [ ]:
data['Age'].mean()

In [ ]:
data['Age'].fillna(data['Age'].mean(), inplace=True)

In [ ]:
data.isnull().sum()

In [ ]:
data.isnull().sum()/data.shape[0]*100

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.isnull().sum()

In [ ]:
data.duplicated().sum()

In [ ]:
import numpy as np

In [ ]:
my_list = [1, 2, 3, 4, 5]

In [ ]:
print(type(my_list))

<class 'list'>


In [ ]:
my_arr = np.array(my_list)

In [ ]:
print(type(my_arr))

<class 'numpy.ndarray'>


In [ ]:
two_d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(two_d)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
three_d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(three_d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
